// AI Mock Interview — реальные вопросы из БД + лайв-кодинг через LLM-судью.
// Финальная оценка от Джарвиса — ранг-оценка интервью.

import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { llm } from '../lib/llm';
import { prisma } from '../lib/prisma';
import {
  DIRECTIONS,
  GRADES,
  getDirectionMeta,
  isAllowed,
  type Direction,
  type Grade,
} from '../lib/mockBank';
import {
  abortSession,
  createSession,
  getSession,
  isExpired,
  rateLimitStatus,
  remainingMs,
  tryConsume,
  canStart,
  recordStart,
  recordCompletion,
  verifySignedCooldown,
  type MockQuestionRuntime,
  type CodingTaskRuntime,
  type MockSession,
  type AntiCheatResult,
  type AnswerRecord,
} from '../lib/mockStore';
import { judgeCode, type JudgeLanguage } from '../lib/codeJudge';
import { loadTasks, pickRandomTasks, type MdTask } from '../lib/mdLoader';

const router = Router();

/* --------------------------- helpers --------------------------- */

function clientIp(req: Request): string {
  const fwd = (req.headers['x-forwarded-for'] as string) ?? '';
  return fwd.split(',')[0].trim() || req.socket.remoteAddress || 'unknown';
}

async function callJson<T>(systemPrompt: string, userPrompt: string, temperature = 0.3): Promise<T> {
  const res = await llm.client.chat.completions.create({
    model: llm.model,
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userPrompt },
    ],
    temperature,
    max_tokens: 1100,
    response_format: { type: 'json_object' },
  });
  const raw = res.choices[0]?.message?.content ?? '{}';
  try { return JSON.parse(raw) as T; }
  catch {
    const cleaned = raw.replace(/```json|```/g, '').trim();
    return JSON.parse(cleaned) as T;
  }
}

function rankFromScore(score: number): { rank: 'D'|'C'|'B'|'A'|'S'|'SS'|'SSS'; label: string } {
  if (score >= 95) return { rank: 'SSS', label: 'SMOKIN\' SEXY STYLE!!!' };
  if (score >= 87) return { rank: 'SS',  label: 'SHOWTIME!!' };
  if (score >= 75) return { rank: 'S',   label: 'STYLISH!' };
  if (score >= 60) return { rank: 'A',   label: 'ALRIGHT!' };
  if (score >= 45) return { rank: 'B',   label: 'BRAVO' };
  if (score >= 30) return { rank: 'C',   label: 'COOL' };
  return { rank: 'D', label: 'DULL' };
}

/* -------------------- anti-cheat: AI marker detection -------------------- */

const ZERO_WIDTH_RE = /[​‌‍﻿⁠⁡⁢⁣⁤­͏؜ᅟᅠ឴឵᠎ -‏‪-‮⁦-⁩￹-￻]/;

// NB: \b не работает с кириллицей в JS — используем (?:^|\s) вместо \b перед кириллицей
const AI_SELF_REF_PATTERNS = [
  /(?:^|\s)я\s*(—|-)?\s*(языковая\s+модель|ии|искусственный\s+интеллект|нейросеть|чат-?бот)/i,
  /\bas\s+an?\s+(ai|language\s+model|llm|chatbot|assistant)\b/i,
  /\bi'?m\s+an?\s+(ai|language\s+model|llm|chatbot)\b/i,
  /(?:^|\s)как\s+(языковая\s+модель|ии(?:\s|,|\.)|нейросеть)/i,
  /(?:^|\s)будучи\s+(языковой\s+моделью|ии(?:\s|,|\.)|нейросетью)/i,
];

const AI_PHRASE_PATTERNS = [
  /(?:^|\s)рад\s+помочь.*вопрос/i,
  /(?:^|\s)надеюсь,?\s+(это\s+)?(поможет|помогло|было\s+полезно)/i,
  /(?:^|\s)если\s+(у\s+вас\s+)?есть\s+(ещё\s+)?вопросы.*обращайтесь/i,
  /(?:^|\s)не\s+стесняйтесь\s+задавать/i,
  /(?:^|\s)обращайтесь,?\s+если/i,
  /(?:^|\s)с\s+удовольствием\s+(отвечу|помогу|объясню)/i,
  /(?:^|\s)давайте\s+разберём\s+это\s+подробнее/i,
  /(?:^|\s)конечно!?\s+давайте\s+разбер/i,
  /(?:^|\s)отличный\s+вопрос!/i,
  /(?:^|\s)хороший\s+вопрос!/i,
  /\bI'?d\s+be\s+happy\s+to\s+(help|explain|assist)/i,
  /\blet\s+me\s+break\s+(this|it)\s+down/i,
  /\bhere'?s?\s+a\s+(comprehensive|detailed)\s+(overview|explanation|breakdown)/i,
  /\b(great|excellent|good)\s+question!/i,
  /\bfeel\s+free\s+to\s+ask/i,
];

const AI_FORMAT_PATTERNS = [
  /[\u{1F4A1}\u{1F4DD}\u{1F4CC}\u{1F4A5}\u{1F4DA}\u{2705}\u{274C}\u{1F525}\u{1F680}\u{1F4AF}\u{1F522}\u{1F4D6}\u{1F4D8}\u{1F4D7}\u{2B50}\u{1F50D}\u{26A0}\u{2728}\u{1F3AF}\u{1F449}\u{1F4E2}\u{1F5C3}\u{1F4C8}\u{1F4CA}\u{1F4B0}\u{1F4CE}\u{1F4CB}\u{1F517}\u{1F914}\u{1F9E0}]/u,
  /#{2,}\s+\S/,
  /\*{2}.+?\*{2}/,
  /```[\s\S]{0,10}\n/,
];

const HF_TOKEN = process.env.HF_TOKEN ?? '';
const HF_MODEL = process.env.HF_ANTICHEAT_URL ?? 'https://router.huggingface.co/hf-inference/models/openai-community/roberta-base-openai-detector';
const OR_KEY = process.env.OPENROUTER_ANTICHEAT_KEY ?? '';
const OR_MODEL = process.env.OPENROUTER_ANTICHEAT_MODEL ?? 'meta-llama/llama-3.3-70b-instruct';

const LLM_DETECT_SYSTEM = `You are an AI-plagiarism detector for a technical interview platform. You receive numbered answers from a candidate. For EACH answer, estimate the probability (0-100) that it was generated by an AI (ChatGPT, Claude, etc.) rather than written by a human during a live interview.

Key signals of AI text: formal/educational tone, structured with headers/bullets, overly comprehensive, "textbook" style, emoji decorations, perfectly balanced explanations, markdown formatting.
Key signals of human text: casual tone, typos, slang, incomplete thoughts, personal experience references, brief/direct answers, informal punctuation.

IMPORTANT: A knowledgeable expert who gives a correct, detailed answer is NOT necessarily AI. Focus on STYLE and naturalness, not correctness or depth.

Respond ONLY with JSON: {"scores": [<score1>, <score2>, ...]}`;

async function hfAiScore(text: string): Promise<number | null> {
  if (!HF_TOKEN || text.length < 40) return null;
  try {
    const r = await fetch(HF_MODEL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${HF_TOKEN}`,
      },
      body: JSON.stringify({ inputs: text.slice(0, 1500) }),
      signal: AbortSignal.timeout(8000),
    });
    if (!r.ok) return null;
    const j = await r.json() as Array<Array<{ label: string; score: number }>>;
    const fake = j?.[0]?.find((c) => c.label === 'Fake');
    return fake ? fake.score : null;
  } catch {
    return null;
  }
}

async function llmAiScores(answers: AnswerRecord[]): Promise<(number | null)[]> {
  if (!OR_KEY || answers.length === 0) return answers.map(() => null);
  const numbered = answers.map((a, i) => `${i + 1}. ${a.userAnswer.slice(0, 500)}`).join('\n');
  try {
    const r = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OR_KEY}`,
      },
      body: JSON.stringify({
        model: OR_MODEL,
        messages: [
          { role: 'system', content: LLM_DETECT_SYSTEM },
          { role: 'user', content: numbered },
        ],
        temperature: 0,
        max_tokens: 200,
        response_format: { type: 'json_object' },
      }),
      signal: AbortSignal.timeout(15000),
    });
    if (!r.ok) return answers.map(() => null);
    const j = await r.json() as any;
    const raw = j?.choices?.[0]?.message?.content ?? '';
    const parsed = JSON.parse(raw) as { scores?: number[] };
    if (Array.isArray(parsed.scores) && parsed.scores.length === answers.length) {
      return parsed.scores.map((s) => (typeof s === 'number' ? s / 100 : null));
    }
    return answers.map(() => null);
  } catch {
    return answers.map(() => null);
  }
}

async function detectAiMarkers(answers: AnswerRecord[]): Promise<AntiCheatResult> {
  const flagged: number[] = [];
  let totalMarkers = 0;

  const [hfScores, llmScores] = await Promise.all([
    Promise.all(answers.map((a) => hfAiScore(a.userAnswer))),
    llmAiScores(answers),
  ]);

  answers.forEach((a, idx) => {
    const text = a.userAnswer;
    let markers = 0;

    if (ZERO_WIDTH_RE.test(text)) {
      const zwCount = (text.match(new RegExp(ZERO_WIDTH_RE.source, 'g')) || []).length;
      if (zwCount >= 2) markers += zwCount;
    }

    for (const re of AI_SELF_REF_PATTERNS) {
      if (re.test(text)) markers += 3;
    }

    for (const re of AI_PHRASE_PATTERNS) {
      if (re.test(text)) markers += 2;
    }

    let fmtHits = 0;
    for (const re of AI_FORMAT_PATTERNS) {
      if (re.test(text)) fmtHits++;
    }
    if (fmtHits >= 2) markers += fmtHits * 2;

    const hf = hfScores[idx];
    if (hf !== null && hf >= 0.75) markers += 4;

    const llm = llmScores[idx];
    if (llm !== null && llm >= 0.70) markers += 5;

    if (markers > 0) {
      flagged.push(idx + 1);
      totalMarkers += markers;
    }
  });

  return {
    cheaterDetected: flagged.length >= 2 || totalMarkers >= 4,
    flaggedAnswers: flagged,
    markerCount: totalMarkers,
  };
}

// Вопросы сессии: топ-150 технических (direction+grade) по частоте встречаемости -> шафл -> берём 15.
const MAX_TECH_PER_INTERVIEW = 15;
const CODING_TASKS_PER_SESSION = 2;

/* --------------------------- public meta --------------------------- */

router.get('/directions', (_req, res) => {
  res.json({ directions: DIRECTIONS, grades: GRADES });
});

router.get('/rate-limit', (req, res) => {
  const ip = clientIp(req);
  const penalty = canStart(ip);
  const legacy = rateLimitStatus(ip);

  // Если penalty разрешает, но weekly limit исчерпан — считаем retryAfter от legacy resetAt
  let retryAfter = penalty.retryAfter;
  if (penalty.ok && legacy.remaining === 0 && legacy.resetAt) {
    retryAfter = Math.max(0, Math.ceil((legacy.resetAt - Date.now()) / 1000));
  }

  res.json({
    allowed: penalty.ok && legacy.remaining > 0,
    retryAfter,
    signedCooldown: penalty.signed,
    legacy,
  });
});

/* --------------------------- start --------------------------- */

const startSchema = z.object({
  direction: z.enum(['frontend', 'java', 'python', 'php', 'csharp']),
  grade: z.enum(['JUNIOR', 'MIDDLE', 'SENIOR']),
});

router.post('/start', async (req: Request, res: Response) => {
  const parsed = startSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: 'bad_request' });

  const { direction, grade } = parsed.data as { direction: Direction; grade: Grade };
  const guard = isAllowed(direction, grade);
  if (!guard.ok) return res.status(400).json({ error: 'unavailable', message: guard.reason });

  const meta = getDirectionMeta(direction);

  const dbDir = await prisma.direction.findUnique({ where: { slug: meta.dbSlug } });
  if (!dbDir) return res.status(500).json({ error: 'db_direction_missing', message: `slug ${meta.dbSlug} не найден в БД` });

  const POOL_SIZE = 150;

  // Пул кандидатов: топ технических вопросов направления нужного грейда,
  // отсортированных по частоте встречаемости в реальных интервью (число привязок к видео).
  async function buildPool(difficulty: string | null) {
    return prisma.question.findMany({
      where: {
        directionId: dbDir!.id,
        type: 'TECHNICAL',
        ...(difficulty ? { difficulty: difficulty as any } : {}),
      },
      select: {
        id: true,
        text: true,
        topic: { select: { name: true } },
        _count: { select: { interviewQuestions: true } },
      },
      orderBy: { interviewQuestions: { _count: 'desc' } },
      take: POOL_SIZE,
    });
  }

  // Берём пул нужного грейда; если вопросов меньше чем нужно на сессию -
  // добираем из всех грейдов направления (на случай маленьких разделов).
  let pool = await buildPool(grade);
  let usedFallback = false;
  if (pool.length < MAX_TECH_PER_INTERVIEW) {
    pool = await buildPool(null);
    usedFallback = true;
  }
  if (pool.length === 0) {
    return res.status(503).json({
      error: 'no_questions',
      message: `Нет технических вопросов для ${meta.label} / ${grade}.`,
    });
  }

  // Fisher-Yates: перемешиваем пул, поэтому каждая сессия - практически уникальный набор.
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  const limited = pool.slice(0, MAX_TECH_PER_INTERVIEW);

  const questions: MockQuestionRuntime[] = limited.map((q) => ({
    id: q.id,
    text: q.text,
    topic: q.topic?.name ?? meta.label,
    kind: 'theory',
  }));

  const sourceLabel = usedFallback
    ? `${meta.label} · случайная подборка`
    : `${meta.label} · ${grade} · случайная подборка`;

  const allTasks = loadTasks(meta.dbSlug, grade);
  if (allTasks.length < CODING_TASKS_PER_SESSION) {
    return res.status(500).json({
      error: 'not_enough_md_tasks',
      message: `В /questions/${meta.dbSlug}/${grade.toLowerCase()}/ нашёл только ${allTasks.length} MD-задач, нужно ≥${CODING_TASKS_PER_SESSION}.`,
    });
  }
  const pickedTasks = pickRandomTasks(allTasks, CODING_TASKS_PER_SESSION);
  const codingRuntime: CodingTaskRuntime[] = pickedTasks.map((t) => ({
    id: t.id,
    title: t.title,
    description: t.description,
    starterCode: t.starterCode,
    language: t.language,
    difficulty: t.difficulty,
    testsCount: t.tests.length,
  }));

  const ip = clientIp(req);

  const penalty = canStart(ip);
  if (!penalty.ok) {
    return res.status(429).json({
      error: 'cooldown',
      retryAfter: penalty.retryAfter,
      signedCooldown: penalty.signed,
    });
  }

  if (!tryConsume(ip)) {
    const status = rateLimitStatus(ip);
    return res.status(429).json({ error: 'rate_limit', ...status });
  }

  recordStart(ip);

  const session = createSession({
    ip, direction, grade,
    questions, codingTasks: codingRuntime,
    sourceInterviewTitle: sourceLabel,
  });
  TASKS_BY_SESSION.set(session.id, new Map(pickedTasks.map((t) => [t.id, t])));

  res.json(serializeForClient(session));
});

const TASKS_BY_SESSION = new Map<string, Map<string, MdTask>>();

/* --------------------------- answer --------------------------- */

const answerSchema = z.object({
  sessionId: z.string(),
  answer: z.string().min(1).max(8000),
});

router.post('/answer', (req: Request, res: Response) => {
  const parsed = answerSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: 'bad_request' });

  const session = getSession(parsed.data.sessionId);
  if (!session) return res.status(404).json({ error: 'session_not_found' });
  if (session.stage === 'aborted') return res.status(400).json({ error: 'aborted' });
  if (session.stage !== 'qa') return res.status(400).json({ error: 'wrong_stage' });
  if (isExpired(session)) {
    session.stage = session.codingTasks.length > 0 ? 'coding' : 'finished';
    return res.json({ session: serializeForClient(session), expired: true });
  }

  const q = session.questions[session.currentQuestionIdx];
  if (!q) return res.status(400).json({ error: 'no_current_question' });

  session.answers.push({
    questionId: q.id,
    questionText: q.text,
    topic: q.topic,
    userAnswer: parsed.data.answer,
  });
  session.currentQuestionIdx += 1;

  if (session.currentQuestionIdx >= session.questions.length) {
    session.stage = session.codingTasks.length > 0 ? 'coding' : 'finished';
  }

  res.json({ session: serializeForClient(session) });
});

/* --------------------------- coding --------------------------- */

const codingSchema = z.object({
  sessionId: z.string(),
  code: z.string().min(1).max(40000),
});

router.post('/coding', async (req: Request, res: Response) => {
  const parsed = codingSchema.safeParse(req.body);
  if (!parsed.success) return res.status(400).json({ error: 'bad_request' });

  const session = getSession(parsed.data.sessionId);
  if (!session) return res.status(404).json({ error: 'session_not_found' });
  if (session.stage === 'aborted') return res.status(400).json({ error: 'aborted' });
  if (session.stage !== 'coding') return res.status(400).json({ error: 'wrong_stage' });
  if (isExpired(session)) {
    session.stage = 'finished';
    return res.json({ session: serializeForClient(session), expired: true });
  }

  const task = session.codingTasks[session.currentCodingIdx];
  if (!task) return res.status(400).json({ error: 'no_current_task' });

  const tasksMap = TASKS_BY_SESSION.get(session.id);
  const fullTask = tasksMap?.get(task.id);
  if (!fullTask) return res.status(500).json({ error: 'tests_not_loaded' });

  let report;
  try {
    report = await judgeCode(task.language as JudgeLanguage, parsed.data.code, fullTask.tests);
  } catch (e: any) {
    console.error('mock/coding judge error', e);
    return res.status(502).json({ error: 'judge_failed', message: e?.message });
  }

  session.coding.push({
    taskId: task.id,
    title: task.title,
    language: task.language,
    userCode: parsed.data.code,
    testsPassed: report.passed,
    testsTotal: report.total,
    errorSample: report.compileError ? `Ошибка компиляции` : report.errorSample,
  });
  session.currentCodingIdx += 1;

  if (session.currentCodingIdx >= session.codingTasks.length) {
    session.stage = 'finished';
  }

  res.json({
    result: {
      taskId: task.id,
      testsPassed: report.passed,
      testsTotal: report.total,
      errorSample: report.compileError ? `Ошибка компиляции` : report.errorSample,
    },
    session: serializeForClient(session),
  });
});

/* --------------------------- abort --------------------------- */

router.post('/abort', (req: Request, res: Response) => {
  const sessionId = String(req.body?.sessionId ?? '');
  const session = abortSession(sessionId);
  if (!session) return res.status(404).json({ error: 'session_not_found' });
  res.json(serializeForClient(session));
});

/* --------------------------- finish --------------------------- */

const FINAL_SYSTEM = `Ты — Джарвис, технический интервьюер уровня tech lead. Сводишь итог собеседования.

ПРИНЦИПЫ ОЦЕНКИ:
- Главный критерий — ПРАВИЛЬНОСТЬ по сути. Краткий, но верный ответ лучше длинного неправильного.
- Если кандидат ответил коротко (1-3 предложения), но СУТЬ передана верно — это хороший ответ, 60-80% от максимума за вопрос.
- Развёрнутый верный ответ с примерами и терминами — это отлично, 80-100%.
- Не штрафуй за краткость, если суть схвачена. Штрафуй за ФАКТИЧЕСКИЕ ошибки и непонимание.
- Бессмысленный набор символов, "не знаю", "хз", пустые отписки = 0 баллов за вопрос.
- Если КАЖДЫЙ ответ — мусор: totalScore 0..8.
- Объективные тесты лайв-кодинга (testsPassed/testsTotal) — жёсткий сигнал. 0 пройденных из N = штраф -15.
- Прерванное собеседование: totalScore максимум 40.

ФОРМАТ (СТРОГО JSON, без markdown):
{
  "totalScore": <0..100>,
  "verdict": "passed" | "failed",
  "summary": "<3-5 предложений на русском, как фидбек после собеса>",
  "strengths":  ["<коротко>", ...],
  "weaknesses": ["<коротко>", ...],
  "toImprove":  ["<совет>", ...]
}

verdict=passed только при totalScore >= 60. Оценивай честно, но справедливо — суть важнее объёма.`;

router.post('/finish', async (req: Request, res: Response) => {
  const sessionId = String(req.body?.sessionId ?? '');
  const session = getSession(sessionId);
  if (!session) return res.status(404).json({ error: 'session_not_found' });

  if (session.finalReport) return res.json(serializeForClient(session));
  if (session.stage !== 'aborted') session.stage = 'finished';

  const qaBlock = session.answers.map((a, i) =>
    `${i + 1}. [${a.topic}] ${a.questionText}\nОтвет кандидата: ${a.userAnswer.slice(0, 600)}`,
  ).join('\n\n');

  const codingBlock = session.coding.map((c, i) =>
    `Задача ${i + 1}: ${c.title} — тесты ${c.testsPassed}/${c.testsTotal}${c.errorSample ? ` (${c.errorSample})` : ''}`,
  ).join('\n');

  const meta = getDirectionMeta(session.direction);
  const aborted = session.stage === 'aborted';
  const unanswered = session.questions.length - session.answers.length;
  const codingMissed = session.codingTasks.length - session.coding.length;

  const userPrompt = `Направление: ${meta.label}. Грейд: ${session.grade}.${aborted ? ' СОБЕСЕДОВАНИЕ ПРЕРВАНО кандидатом.' : ''}
Не ответил на вопросов: ${unanswered}. Не сдал кодинг-задач: ${codingMissed}.

ОТВЕТЫ:
${qaBlock || '(нет ответов)'}

ЛАЙВ-КОДИНГ (объективные тесты):
${codingBlock || '(не было задач)'}

Дай финальную оценку.`;

  const antiCheat = await detectAiMarkers(session.answers);

  if (antiCheat.cheaterDetected) {
    session.finalReport = {
      totalScore: 0,
      rank: 'F',
      rankLabel: 'ЧИТЕР',
      verdict: 'cheater',
      summary: 'Система нашла явные AI-маркеры в нескольких ответах. Это не эвристика по "похожести на ИИ", а проверка на прямые маркеры вроде AI-самоописания или скрытых служебных символов.',
      strengths: [],
      weaknesses: ['использование ИИ для генерации ответов'],
      toImprove: ['пройти собеседование самостоятельно, без помощи языковых моделей'],
      antiCheat,
    };
    return res.json(serializeForClient(session));
  }

  let aiOut: any;
  try {
    aiOut = await callJson<{
      totalScore: number;
      verdict: 'passed' | 'failed';
      summary: string;
      strengths: string[];
      weaknesses: string[];
      toImprove: string[];
    }>(FINAL_SYSTEM, userPrompt, 0.25);
  } catch (e: any) {
    console.error('mock/finish ai error', e);
    const codingScore = session.coding.length === 0 ? 0
      : (session.coding.reduce((s, c) => s + (c.testsTotal ? c.testsPassed / c.testsTotal : 0), 0) / session.coding.length) * 100;
    const qaCoverage = session.questions.length === 0 ? 0 : (session.answers.length / session.questions.length) * 100;
    const fallback = Math.round(codingScore * 0.55 + qaCoverage * 0.45);
    aiOut = {
      totalScore: aborted ? Math.min(fallback, 40) : fallback,
      verdict: fallback >= 60 ? 'passed' : 'failed',
      summary: aborted
        ? 'Собеседование было прервано кандидатом. Итог посчитан по факту: автотесты + ответы.'
        : 'Сводка автоматическая (Джарвис недоступен): балл = тесты × 0.55 + покрытие вопросов × 0.45.',
      strengths: [], weaknesses: aborted ? ['прервал собеседование'] : [],
      toImprove: ['пройти ещё раз без прерываний'],
    };
  }

  const totalScore = Math.max(0, Math.min(100, Number(aiOut.totalScore) || 0));
  const r = rankFromScore(totalScore);

  session.finalReport = {
    totalScore,
    rank: r.rank,
    rankLabel: r.label,
    verdict: aiOut.verdict === 'passed' ? 'passed' : 'failed',
    summary: aiOut.summary ?? '',
    strengths:  Array.isArray(aiOut.strengths)  ? aiOut.strengths.slice(0, 4)  : [],
    weaknesses: Array.isArray(aiOut.weaknesses) ? aiOut.weaknesses.slice(0, 4) : [],
    toImprove:  Array.isArray(aiOut.toImprove)  ? aiOut.toImprove.slice(0, 5)  : [],
    antiCheat: antiCheat.flaggedAnswers.length > 0 ? antiCheat : undefined,
  };

  recordCompletion(session.ip);

  res.json(serializeForClient(session));
});

router.get('/session/:id', (req, res) => {
  const session = getSession(req.params.id);
  if (!session) return res.status(404).json({ error: 'session_not_found' });
  res.json(serializeForClient(session));
});

function serializeForClient(s: MockSession) {
  const currentQuestion = s.stage === 'qa' ? s.questions[s.currentQuestionIdx] ?? null : null;
  const currentCoding = s.stage === 'coding' ? s.codingTasks[s.currentCodingIdx] ?? null : null;
  const meta = getDirectionMeta(s.direction);
  return {
    id: s.id,
    direction: s.direction,
    directionLabel: meta.label,
    grade: s.grade,
    stage: s.stage,
    sourceInterviewTitle: s.sourceInterviewTitle,
    durationMs: s.durationMs,
    startedAt: s.startedAt,
    remainingMs: remainingMs(s),
    totalQuestions: s.questions.length,
    totalCoding: s.codingTasks.length,
    answers: s.answers,
    coding: s.coding,
    currentQuestion,
    currentCoding,
    currentQuestionNumber: s.currentQuestionIdx + 1,
    currentCodingNumber: s.currentCodingIdx + 1,
    finalReport: s.finalReport ?? null,
  };
}

export default router;
