#!/bin/bash
# Применение очистки на СЕРВЕРЕ (apply не требует ключа OpenRouter)
# Запусти: bash clean-apply-all.sh

echo 'Применяю очистку (мусор + дубли) по всем направлениям...'

echo '========== 1c =========='
npm run junk:apply 1c
npm run dedupe:apply 1c
echo '========== 3d-artist =========='
npm run junk:apply 3d-artist
npm run dedupe:apply 3d-artist
echo '========== ai-engineer =========='
npm run junk:apply ai-engineer
npm run dedupe:apply ai-engineer
echo '========== android =========='
npm run junk:apply android
npm run dedupe:apply android
echo '========== aqa =========='
npm run junk:apply aqa
npm run dedupe:apply aqa
echo '========== business-analyst =========='
npm run junk:apply business-analyst
npm run dedupe:apply business-analyst
echo '========== cpp =========='
npm run junk:apply cpp
npm run dedupe:apply cpp
echo '========== csharp =========='
npm run junk:apply csharp
npm run dedupe:apply csharp
echo '========== data-analyst =========='
npm run junk:apply data-analyst
npm run dedupe:apply data-analyst
echo '========== data-engineer =========='
npm run junk:apply data-engineer
npm run dedupe:apply data-engineer
echo '========== data-science =========='
npm run junk:apply data-science
npm run dedupe:apply data-science
echo '========== devops =========='
npm run junk:apply devops
npm run dedupe:apply devops
echo '========== frontend =========='
npm run junk:apply frontend
npm run dedupe:apply frontend
echo '========== go =========='
npm run junk:apply go
npm run dedupe:apply go
echo '========== java =========='
npm run junk:apply java
npm run dedupe:apply java
echo '========== php =========='
npm run junk:apply php
npm run dedupe:apply php
echo '========== product-manager =========='
npm run junk:apply product-manager
npm run dedupe:apply product-manager
echo '========== python =========='
npm run junk:apply python
npm run dedupe:apply python
echo '========== qa =========='
npm run junk:apply qa
npm run dedupe:apply qa
echo '========== reverse-engineer =========='
npm run junk:apply reverse-engineer
npm run dedupe:apply reverse-engineer
echo '========== rust =========='
npm run junk:apply rust
npm run dedupe:apply rust
echo '========== seo =========='
npm run junk:apply seo
npm run dedupe:apply seo
echo '========== unity =========='
npm run junk:apply unity
npm run dedupe:apply unity
echo 'ГОТОВО'
